version: '3.8'
name: graceful-shutdown
services: 
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      mongo:
        condition: service_healthy
      rabbit:
        condition: service_healthy
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.12.10-alpine
    ports: 
      - '5672:5672'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      start_period: 20s
      interval: 10s
      timeout: 10s
      retries: 3  
  mongo:
    container_name: mongo
    image: mongo:7-jammy
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
